### ISSUE TITLE
Broken build on windows

### ISSUE THREAD

**Issue by DotsElshad** [christkv/kerberos#10]
Hello,

the commit 2071840169ae3e7370f3cb0a6a9a7ae87058c038 breaks the build on windows. Wrong sources are included and the compiler cannot find "gssapi.h".
Either the global list of sources has to be moved to a OS="linux" condition or the platform specific sources have to be excluded for the windows platform.

Could you please fix this?
Thank you.
Elshad Shirinov

**Comment by scottbea** [comment]
I found the same problem on Ubuntu 14.10. We had to search for the right apt-get package to install the GSSAPI dev libraries (including gssapi.h that you cited above).  For people on Ubuntu, this solved it for us:

``$ sudo apt-get install krb5-multidev``

**Comment by MystK** [comment]
I am also have an issue with building karma on Windows. Has anyone found a fix?

**Comment by christkv** [comment]
http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/
