### ISSUE TITLE
Doesn't work with HTTP instead of mongo?

### ISSUE THREAD

**Issue by bnovc** [christkv/kerberos#13]
If I'm understanding Kerberos correctly, I think what I am wanting to pass in is:

kerberos.authGSSClientInit('HTTP/foo-webservices.bar.com@barCONNECT.bar.COM', Kerberos.GSS_C_NO_OID

This is working fine from a Python module that I'm looking at that calls with the same parameter to gss_import_name.

However, when I run this with this module, I get:

{ [Error:  Miscellaneous failure (see text), Error from KDC: LOOKING_UP_SERVER while looking up 'HTTP\/foo-webservices.apple.com/barconnect.bar.com@OD.bar.COM' (cached result, timeout in 1198 sec)l] code: -1 }

Where it's automatically adding in the OD entry.

I think this might be because GSS_C_NO_OID isn't being passed through:

   maj_stat = gss_import_name(&min_stat, &name_token, gss_krb5_nt_service_name, &state->server_name);                                                

but I haven't recompiled your module yet to confirm that.  gss_krb5_nt_service_name seems hardcoded.

Am I understanding how this should be used?  Is it only meant to work with mongo right now?  Sorry I don't have a totally clear picture on how GSSAPI works yet.

**Comment by christkv** [comment]
yes only works with mongodb. I'm happy to consider pull requests that extend the usage but have not time to do this myself.
