### ISSUE TITLE
Build issue on Windows with Node 0.12 64 bit

### ISSUE THREAD

**Issue by wiredprairie** [christkv/kerberos#15]
After an hour of exploration, I can't find what's causing this error when trying to install this package.

    npm install kerberos

With Windows 8.1, Visual Studio 2013 and Node 0.12 64 bit installed:

    D:\TEMP>npm install kerberos
        \
       > kerberos@0.0.8 install D:\TEMP\node_modules\kerberos
       > (node-gyp rebuild 2> builderror.log) || (exit 0)

    D:\TEMP\node_modules\kerberos>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      kerberos.cc
      worker.cc
      security_buffer.cc
      security_buffer_descriptor.cc
      security_context.cc
      security_credentials.cc
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib
    \win32\wrappers\security_buffer.cc) [D:\TEMP\node_modules\kerberos\build\kerberos.vcxproj]
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib
    \win32\wrappers\security_buffer_descriptor.cc) [D:\TEMP\node_modules\kerberos\build\kerberos.vcxproj]
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib
    \win32\wrappers\security_context.cc) [D:\TEMP\node_modules\kerberos\build\kerberos.vcxproj]
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib
    \win32\wrappers\security_credentials.cc) [D:\TEMP\node_modules\kerberos\build\kerberos.vcxproj]
    C:\Program Files (x86)\Windows Kits\8.1\Include\shared\sspi.h(86): error C2146: syntax error : missing ';' before identifier 'SEC_WCHAR' (..\lib\win32\wrappers\security_context.cc
    ) [D:\TEMP\node_modules\kerberos\build\kerberos.vcxproj]
    C:\Program Files (x86)\Windows Kits\8.1\Include\shared\sspi.h(86): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\lib\win32\wrappers

The same error occurs with 32 bit. 

There are actually hundreds of more errors and at this point, I assume they're all related to whatever the core issue is. Any assistance would be appreciated.

**Comment by smartmouse** [comment]
Did they confirm supporting windows 8? I can npm install kerberos okay on window 7 using node.0.12

**Comment by christkv** [comment]
You have to build using the visual studio command prompt not the node.js one as there is like a million different environmental settings that need to be setup.

**Comment by javilopezc** [comment]
Hey christkv, can you elaborate a bit more on the procedure to build from VS cmd?

**Comment by alanosman** [comment]
Hey guys. I am having the same issue.  Can either of you elaborate on how to resolve this problem?  Any help would be appreciated. thx

**Comment by swxy** [comment]
Hi. I am having the same issue on mac os x Yosemite, Any help would be appreciated, thanks

**Comment by alanosman** [comment]
swxy - I did eventually get mine working on Windows 10.  One thing I did was to completely remove all my node_modules, do a npm cache clean and then try reinstalling.  The issue stems from the fact that NPM doesn't always update dependencies, especially if they have changed.  Hope that helps.
