### ISSUE TITLE
npm install kerberos error

### ISSUE THREAD

**Issue by artakvg** [christkv/kerberos#21]
Trying to install kerberos via npm and getting errors.
Here is what I found in builderror.log
>>>>>>>>>
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/azureuser/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build
.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "node" "/home/azureuser/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/azureuser/workspace/dashboard/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

>>> I have installed node-gyp globally , also I am using ubuntu 14.04.  Any ideas ?

**Comment by artakvg** [comment]
After installing     libkrb5-dev    I got those warnings in builerror.log
Is it OK to continue to use it with those warnings ?

../lib/kerberosgss.c:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:28:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:350:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:692:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^

**Comment by christkv** [comment]
you are probably compiling with gcc so probably why you are getting the warnings. they should not impact anything.

**Comment by artakvg** [comment]
@christkv  installing *libkrb5-dev* is important , that's fixed the errors I got. Think there should be some improvement related to that.

**Comment by stigok** [comment]
Excellent. On openSUSE, it can be installed with `sudo zypper in krb5-devel`

**Comment by wulfsolter** [comment]
Thanks @artakvg. On Ubuntu / Debian, it can be installed with `sudo apt-get install libkrb5-dev`

**Comment by jcrben** [comment]
Can this be fixed upstream so everyone does not have to install `libkrb5-dev`? There's a lot of people using mongo and this seems to be cascading to hit a lot of us. And I know it wasn't happening before.

**Comment by alpharigel** [comment]
Agreed with @jcrben. This affected my mongodb install on a Debian Jesise OS on a Rasberry Pi.

**Comment by christkv** [comment]
2.0.47 let's it fail fully as an optional dependency but other than that there is no practical way to detect system dependencies before trying to install.

**Comment by markstos** [comment]
@christkv Which package are you referring to the 2.0.47 version of?

**Comment by ChristianRich** [comment]
What is the fix for Linux? Install libkrb5-dev?

**Comment by markstos** [comment]
@ChristianRich, Amazon EC2 runs multiple distributions of Linux. In my case, on Ubuntu 14.04, I found that the message was a false alarm and was not actually causing the installation to fail. Our problem was unrelated.   We still plan to eventually upgrade Mongoose, which will upgrade the MongoDB dependency, which will upgrade the kerberos dependency and cause the warning to go away.

**Comment by capaj** [comment]
@wulfsolter thanks, installling libkrb5-dev fixed it for me

**Comment by pawsong** [comment]
On ec2 instance with amazon linux (redhat thing), `sudo yum install krb5-devel` fixed failing installation despite leaving some warning messages.

**Comment by ChristianRich** [comment]
Awesome. Thanks @pawsong for supplying this info.

**Comment by bomb1e** [comment]
Doing sudo apt-get install libkrb5-dev worked for me on Ubuntu 15.04

**Comment by owaishanif786** [comment]
running  sudo apt-get install libkrb5-dev fixed for ubuntu 14.04

**Comment by seanfuture** [comment]
why is this issue closed when it's still a problem today unless libkrb5-dev is installed?

**Comment by jackycute** [comment]
same here, this issue should be open

**Comment by christkv** [comment]
This is no longer an issue when using the 2.1.7 or higher as kerberos is an optional install. Installing the kerberos module is also mentioned in the install guide for the driver at.

http://mongodb.github.io/node-mongodb-native/2.1/getting-started/installation-guide/

**Comment by mhart** [comment]
For anyone stumbling across this on Alpine, I believe the package is `krb5-dev`: https://pkgs.alpinelinux.org/package/v3.4/main/armhf/krb5-dev

**Comment by VadimShvetsov** [comment]
For Alpine as @mhart said the proper package is `krb5-dev`, but not forget to use --update, or it wouldn't be installed.

`apk add --no-cache --update krb5-dev`

**Comment by ict-programmer** [comment]
On OpenSUSE Leap 42.3, I ran `sudo zypper in krb5-devel` and the error got resolved

**Comment by NikIvan** [comment]
Resolved issue on **Amazon Linux AMI** with `sudo yum install krb5-devel.x86_64`

**Comment by anupamhaldkar** [comment]
for Window , how should I install kerberos
