### ISSUE TITLE
Doesn't work with node v4.0.0

### ISSUE THREAD

**Issue by doctorrustynelson** [christkv/kerberos#25]
Need to upgrade to nan v2.0.9.

**Comment by Sparragus** [comment]
I can confirm that it is not working with v4.0.0

**Comment by bazineta** [comment]
See PR #24.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by dmansfield** [comment]
It works for me (latest master plus some unrelated additions) with this version:
```Now using node v4.1.0 (npm v2.14.3)```
(using nvm on Fedora 22).

And according to npm output it's using:
```nan@2.0.9 node_modules/nan```

So nan 2.0.9 and/or latest commits seems to fix it.

**Comment by ChALkeR** [comment]
#24 was merged. If this works, I believe the ticket could be closed.

**Comment by doctorrustynelson** [comment]
The latest release works.  Closing this issue.
