### ISSUE TITLE
npm install kerberos fatal error on redHat 7 with node version 4.1

### ISSUE THREAD

**Issue by smartmouse** [christkv/kerberos#28]
node@04 test]$ npm install kerberos
/
> kerberos@0.0.14 install /svt/node/test/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/svt/node/test/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/svt/nodebot/testIvy/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/svt/shared/JOYENT32_41/lib/node_modules/npm/node_modul
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.1.2.el7.x86_64
gyp ERR! command "/svt/shared/JOYENT32_41/bin/node" "/svt/shared/JOYENT32_41/lib/node_modules/npm/
gyp ERR! cwd /svt/node/test/node_modules/kerberos
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by christkv** [comment]
you are missing the MIT kerberos library and headers
