### ISSUE TITLE
krb5 docs and dependency

### ISSUE THREAD

**Issue by braydonf** [christkv/kerberos#30]
Received this error message during installation:
```js
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
```

After installing krb5, with the below command, the message was cleared:

`apt-get install libkrb5-dev`

It looks like the package may have been outdated.

**Comment by christkv** [comment]
I've documented it here, that the mit kerberos extension is needed.

http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/
