### ISSUE TITLE
Unable to install on WIndows 10

### ISSUE THREAD

**Issue by danwellman** [christkv/kerberos#32]
I have a 64bit machine, Windows 10 and Visual Studio 2015 and I am finding it impossible to install kerberos, or more specifically, other modules (sails-mongo) which use kerberos.

This is the full output in the console:

kerberos@0.0.15 install C:\Users\Dan\dashboard\node_modules\sails-mongo\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
> (node-gyp rebuild) || (exit 0)

if not defined npm_config_node_gyp (node "C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Dan\AppData\Roaming\npm\node_modules\kerberos\build\kerberos.vcxproj(20,3): error MSB4019: The import ed project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props" was not found.  Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Dan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dan\AppData\Roaming\npm\node_modules\kerberos
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
kerberos@0.0.15 C:\Users\Dan\AppData\Roaming\npm\node_modules\kerberos
└── nan@2.0.9

I've tried installing kerberos globally and see the same output. I was originally using Node 4.0.2 and NPM 3.3.6, but I've also tried reverting to Node 0.12.6 and NPM 2.14.5 and still see the same error. I've installed a bunch of Windows SDKs and updates. I've tried installing with `--msvs_version=2013` and `--msvs_version=2015` flags. Nothing is working.

**Comment by christkv** [comment]
this is the only tool chain I've had success with previously. you also have to build from the visual studio command prompt.

http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/

**Comment by craigvl** [comment]
Hey thanks for this response as I am also having this issue, just wondering if the success that you have had with the above tool chain has worked with node v4?

**Comment by christopherhardie1** [comment]
I also am facing the a similar problem on windows, but for me at least it has more to do with version 4 of node.  For me, this package installs  using node 0.12 but not with 4. I have many different combinations of Visual studio installations and command line parameters as suggested on different sites, and spent hours doing so. I have even tried different Windows OS (server 2012, windows 7 and windows 10). Has anyone else been able to install this package in node version 4? Even if someone could confirm that it is possible that would be great so I can know if it is worth keeping trying or not.  Thanks in advance.

**Comment by MarcoWilliamsPF** [comment]
This is the resolution for this issue: 
`npm config set msvs_version 2013 --global`

see - http://stackoverflow.com/questions/33183161/node-gyp-error-tracker-error-trk0005-failed-to-locate-cl-exe-the-system-c

**Comment by danwellman** [comment]
I found that installing the Community edition of Visual Studio 2015 fixed this and other similar issues
