### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SylvainEstevez** [christkv/kerberos#35]
Hi there,
We would be interested by this module and saw it has been dowloaded several times already.

Could you tell us where to find the documentation ?

Many thanks,
Best,
Sylvain

**Comment by christkv** [comment]
Hi Sylvain the module was written just for the mongodb driver but was then extended by others to allow for more general kerberos usage. However I've no experience in using it outside of the node driver. you might be able to find more of what you need here

https://www.npmjs.com/package/passport-negotiate

As they've used the kerberos module to implement http auth it seems. If you do use the module I would love any contributions about how to use it for whatever use case you are planning.
