### ISSUE TITLE
Dependencise not listed

### ISSUE THREAD

**Issue by aviemet** [christkv/kerberos#39]
Tried to install mongoose for a while, kept getting kerbose make errors and failures. After consulting the docs for both with no help, found a solution on StackOverflow suggesting that `libkrb5-dev` is a dependency. Could all the dependencies be listed for this library please?

**Comment by christkv** [comment]
docs where updated a while ago http://mongodb.github.io/node-mongodb-native/2.1/getting-started/installation-guide/
