### ISSUE TITLE
MSVC++ 2010 Build errors

### ISSUE THREAD

**Issue by Badestrand** [christkv/kerberos#40]
Hi

Mongoose has a dependency on kerberos but I can't get it to build on Windows 10. I have Visual Studio C++ 2010 installed but even when trying to build from the project files I get hundred of errors.

All errors seem to come from v8.h, e.g. for the lines
```
template <class T>
using Handle = Local<T>;
```
Those template aliases are from the C++11 standard and **not supported** on MSVC++ 2010 ([link](https://msdn.microsoft.com/en-us/library/hh567368.aspx#corelanguagetable)). I have version Node.js 4.2.4 and node-gyp is 3.2.1.

I guess the template aliases from v8.h got into the code in newer versions of node.js?`So I guess kerberos is not possible to build with MSVC++ 2010 and current version of node-gyp?

That leaves the question: Which version of node and node-gyp do I need so building is no problem?

**Comment by christkv** [comment]
probably the 0.12.x branch, you should also probably open a node ticket for this on the node and nan projects.

**Comment by christkv** [comment]
you could try the latest community visual studio in case it includes an updated compiler

**Comment by Badestrand** [comment]
Thank you for your replies. Yes, I think it should work with the newer compilers but the page states *Visual Studio C++ 2010 (do not use higher versions)*. However MSVC++ 2012 also didn't work and I currently don't have the space on my SSD for the >11 GB for the 2015 version so I will give up right now... But thank you for your quick replies! :)

**Comment by Badestrand** [comment]
Woah, finally. MSVC++ 2015 didn't work as well but now MSVC++ 2013 did the trick :)

[https://www.microsoft.com/en-us/download/details.aspx?id=44914](Download MSVC++ 2013 Express) and then the command `npm config set msvs_version 2013 --global`

Hope that will help someone one day.
