### ISSUE TITLE
Unclean npm package

### ISSUE THREAD

**Issue by mlazarov** [christkv/kerberos#41]
Hi,
currently the npm package contains file `builderror.log` it breaks building of rpm packages (because rpmbuild checks for error logs like this one and fails hard).

Can you please remove this file and bump the version?

**Comment by christkv** [comment]
done, published as 0.0.18 should be picked up automatically when reinstalling the driver, once it's replicated from the EMEA npm instance

**Comment by mlazarov** [comment]
Thank you!
