### ISSUE TITLE
Are there any way to get this module without using python and C++?

### ISSUE THREAD

**Issue by SCLeoX** [christkv/kerberos#47]
We are trying to get [MongoDB driver for Node.js](https://github.com/mongodb/node-mongodb-native). But they required this module. We, however, are not interested to install python or C++ compilers. Are there any way to get already compiled this package with npm or other tool?

**Comment by christkv** [comment]
We don't provide pre-compiled modules due to the mess of v8 ABI API changes. My suggestion is to compile and use shrink-wrap.

**Comment by SCLeoX** [comment]
Thank you for replying but I do not really understand what you mean by "shrink-wrap". Is that means I compile it and bundle it with the source?

**Comment by christkv** [comment]
I would prebuild on one machine and just copy over. However if you don't plan to use Kerberos you don't need the dependency for the 2.1 series of the driver.

**Comment by SCLeoX** [comment]
You life saver. Thanks so much. :)
