### ISSUE TITLE
Node6 support

### ISSUE THREAD

**Issue by asaf** [christkv/kerberos#50]
Hey,

Seems like 0.0.20 should support node6, 

Requiring the kerberos package causes:

**(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated**
**(node) and will stop working in the next major release.**

==== JS stack trace =========================================

Security context: 0x2c2caa5c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x3843caedaee4] (this=0xcd7d0eed751 <an Object with map 0x1365d1e17be1>#1#,module=0x10d0b03f9 <a Module with map 0x1365d1e181b9>#2#,filename=0x10d0b03d1 <String[87]: /project/node_modules/kerberos/build/Release/kerberos.node>)
    2: load [module.js:456] [pc=0x3843cad38e72] (this=0x10d0b03f9 <a Module with map 0x1365d1e181b9>#2#,filename=0x10d0b03d1 <String[87]: /project/node_modules/kerberos/build/Release/kerberos.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x3843cad3899d] (this=0x2c2caa504189 <undefined>,module=0x10d0b03f9 <a Module with map 0x1365d1e181b9>#2#,filename=0x10d0b03d1 <String[87]: /project/node_modules/kerberos/build/Release/kerberos.node>)

(Stack trace is huge, so I only copied the initial lines)

Thanks.

**Comment by christkv** [comment]
Indeed it does throw warnings but work. I have updated the nan.h package and published 0.0.21 so the warnings should now be gone.

**Comment by asaf** [comment]
yea it worked, was just annoying, tested, looks good, thanks!
