### ISSUE TITLE
Can't get kerberos to isntall. Keeps on throwing gssapi/gssapi.h

### ISSUE THREAD

**Issue by TheMasteredPanda** [christkv/kerberos#57]
Ayo,

I'm basically banging my head on the table so hard I'm bleeding. I have been searching for a resolution for this since this morning! 

I keep on getting this stacktrace when I try `pip install kerberos` https://gyazo.com/264be3678f8297b1e7bdd7d6967b219d

What do I do to resolve this. I'm begging you.

Thanks,
Duke.

**Comment by christkv** [comment]
unfortunately you are looking at the wrong module, you want the python kerberos module.

https://github.com/gaussgss/python-kerberos
